spring:
  datasource:
    url: jdbc:mysql://192.168.0.127:3306/zl_wms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: aa123456
    driver-class-name: com.mysql.jdbc.Driver
